language: objective-c

osx_image: xcode7.3

before_install:
  - gem install cocoapods
  - gem install xcpretty

script:
# Fails with "Unable to find Analytics/TestFlight".
# - pod lib lint --allow-warnings
  - make install
  - make test

notifications:
  email: false